version: '3.8'

services:
  nginx:
    container_name: nginx
    image: s10c106-nginx:${TAG}
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - jenkins-network
    volumes:
      - /policy:/usr/share/nginx/html
    depends_on:
      - back

  front:
    container_name: front
    image: s10c106-front:${TAG}
    build:
      context: ../front
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - jenkins-network

  back:
    container_name: back
    image: s10c106-back:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - jenkins-network
    volumes:
      - ~/redis/data:/data
    user: root
    ports:
      - "6379:6379"

networks:
  jenkins-network:
    external: true