version: '3'
services:
  back:
    image: leikra/back:1.5
    build: .
    environment:
      - USE_PROFILE=prod
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
